version: '3'

services:
  flaskproject:
    build: ./flaskproject
    volumes:
      - ./flaskproject:/usr/src/app
    ports:
      - 5001:80

  website:
    image: php:apache
    volumes:
      - ./php:/var/www/html
    ports:
      - 5000:80
    depends_on:
      - flaskproject

  db:
    image: postgres
  web:
    build: ./st1
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - ./st1:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
