# Generated by Django 2.1.1 on 2018-10-27 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='name',
            field=models.CharField(max_length=264),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='surname',
            field=models.CharField(max_length=264),
        ),
    ]
