# Generated by Django 2.1.1 on 2018-10-27 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0006_typesite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='website',
            name='type',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='exercise.TypeSite'),
        ),
    ]
