# Generated by Django 2.1.1 on 2018-10-27 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0011_remove_website_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='type',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='exercise.TypeSite'),
        ),
    ]
