# Generated by Django 2.1.1 on 2018-10-27 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0012_website_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='website',
            name='type',
        ),
    ]
